### ISSUE TITLE
threadsafety

### ISSUE THREAD

**Issue by eduarddrenth** [HuygensING/visitei#1]
Hi, was just lokking around....

From the javadoc on XPath: An XPath object is not thread-safe and not reentrant.

So what happens in https://github.com/HuygensING/visitei/blob/master/src/main/java/nl/knaw/huygens/tei/xpath/XPathUtil.java is a big risk

**Comment by brambg** [comment]
Thanks for the tip, commit https://github.com/HuygensING/visitei/commit/a2172ae45811c24290e128a2df2b184fb9cc4c44 should fix it.

What's your interest in the visitei project?

**Comment by eduarddrenth** [comment]
Well...

I am working at the Fryske Akademy, we will use TEI for our corpora,
already spoke to Peter Boot about that and the possibilities to process
this TEI material using standard tooling for example for doing (linguistic)
research, but also for presentation.

See also this:
https://bitbucket.org/teibestpractices/linguistic-customization
